### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by d-adamkiewicz** [YahooArchive/locator-handlebars#17]
for YUI 3.13.0 (page.handlebars) for YUI 3.18.0 (page.handlebars) TypeError: templateSpec.call is not a function
for YUI 3.18.0 (page.handlebars) it produces on console: Error: No environment passed to template

**Comment by caridy** [comment]
most likely you have multiple handlebars engines (or YUI versions) competing. Do `npm list yui handlebars` to see the dependency structure.

**Comment by d-adamkiewicz** [comment]
I had old version of 'locator' module (12 of march 2014 - date of files modyfication ).
I cleared 'node_modules' folder and installed all required modules
now  I get on server start

loca.plug(new LocatorHandlebars({ format: 'yui' }))
     ^
TypeError: Object #<Object> has no method 'plug'
 at Object.<anonymous> (/home/nodeusr/locator-handlebars-example/app.js:31:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by caridy** [comment]
that is correct, you have to lockdown locator to `0.3.10` since that's the latest version that supports plugins. 1.x does not support plugins anymore, check the release notes: https://github.com/yahoo/locator/releases
